### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by npedrini** [mbouclas/loopback-component-mailchimp#5]
Does this library support submitting tags when subscribing a user? It doesn't look like it, but I want to check if I'm wrong or if there's a known workaround.

My use case is that I want to set up an email series for users only, and would ideally like to be able to just subscribe them on app sign-up, and be able to segment them via the tag on the MailChimp side. Thanks!

**Comment by mbouclas** [comment]
It doesn't but feel free to submit a PR

**Comment by mbouclas** [comment]
Thank you for the PR. Published
